-- Create a table for public profiles (linked to Telegram users)
create table users (
  id bigint primary key, -- Telegram User ID
  username text,
  first_name text,
  last_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table users enable row level security;

-- Policy: Allow anyone to insert/update their own profile (based on ID, but initially we might just allow public access for simplicity with the anon key if we handle auth manually in the app, 
-- BUT ideally we use Supabase Auth. Since we are using Telegram Auth "outside" of Supabase native auth for now (using the ID directly), we might need to be careful with RLS.
-- For this MVP/Demo, we might keep RLS open or simple.)
create policy "Public profiles are viewable by everyone." on users for select using (true);
create policy "Users can insert their own profile." on users for insert with check (true);
create policy "Users can update their own profile." on users for update using (true);

-- Expenses Table
create table expenses (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) not null,
  title text not null,
  amount numeric not null,
  category text not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Incomes Table
create table incomes (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) not null,
  source text not null,
  amount numeric not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Assets Table
create table assets (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) not null,
  name text not null,
  amount numeric not null,
  type text not null, -- 'cash' | 'bank' | 'crypto' | 'investment' | 'other'
  currency text not null default 'USD'
);

-- Settings Table
create table settings (
  user_id bigint references users(id) primary key,
  currency text default 'USD',
  monthly_budget numeric default 1000,
  theme text default 'light'
);

-- RLS for Data Tables (Simple ID check)
alter table expenses enable row level security;
alter table incomes enable row level security;
alter table assets enable row level security;
alter table settings enable row level security;

-- Policies (We are using the 'user_id' column to filter. 
-- Since we aren't using Supabase Auth JWTs explicitly yet, we need to allow access via the API key. 
-- WARNING: This is less secure for production but fine for this MVP/Demo phase. 
-- In a real app, we'd sign a JWT with the Telegram data. For now, we will allow all operations but relying on the client to send the right ID. 
-- To make it slightly better, we'll just enable public access for now or specific policies if we had the auth context.)

-- For simplicity in this iteration without a backend signer:
create policy "Enable all access for all users" on expenses for all using (true) with check (true);
create policy "Enable all access for all users" on incomes for all using (true) with check (true);
create policy "Enable all access for all users" on assets for all using (true) with check (true);
create policy "Enable all access for all users" on settings for all using (true) with check (true);
ALTER TABLE users ADD COLUMN IF NOT EXISTS password text;
